# Automatic CI that runs conditionally when [ci] is found in head commit message or pull request.
# Manually run with workflow_dispatch.
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    if: >
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[ci]')) ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[ci]')) ||
      github.event_name == 'workflow_dispatch'

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pytest
          fi

      - name: Run tests
        run: |
          python -m pytest -q
